item_prices = {
    "A": 50,
    "B": 30,
    "C": 20,
    "D": 15,
    "E": 40,
    "F": 10,
    "G": 20,
    "H": 10,
    "I": 35,
    "J": 60,
    "K": 70,
    "L": 90,
    "M": 15,
    "N": 40,
    "O": 10,
    "P": 50,
    "Q": 30,
    "R": 50,
    "S": 20,
    "T": 20,
    "U": 40,
    "V": 50,
    "W": 20,
    "X": 17,
    "Y": 20,
    "Z": 21,
}

special_offers = {
    "A": [{"quantity": 5, "price": 200}, {"quantity": 3, "price": 130}],
    "B": [{"quantity": 2, "price": 45}],
    "E": [{"quantity": 2, "free_item": "B"}],
    "F": [{"quantity": 3, "free_item": "F"}],
    "H": [{"quantity": 10, "price": 80}, {"quantity": 5, "price": 45}],
    "K": [{"quantity": 2, "price": 120}],
    "N": [{"quantity": 3, "free_item": "M"}],
    "P": [{"quantity": 5, "price": 200}],
    "Q": [{"quantity": 3, "price": 80}],
    "R": [{"quantity": 3, "free_item": "Q"}],
    "S": [{"quantity": 3, "price": 45}],
    "T": [{"quantity": 3, "price": 45}],
    "U": [{"quantity": 3, "free_item": "U"}],
    "V": [{"quantity": 3, "price": 130}, {"quantity": 2, "price": 90}],
    "X": [{"quantity": 3, "price": 45}],
    "Y": [{"quantity": 3, "price": 45}],
    "Z": [{"quantity": 3, "price": 45}],
}

group_items = ["S", "T", "X", "Y", "Z"]
